jobs:
  lint:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Setup node ${{ matrix.node-version }} in ${{ runner.OS }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - continue-on-error: true
      name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        key: ${{ runner.OS }}-${{ matrix.node-version }}-node-${{ hashFiles('**/package-lock.json')
          }}
        path: ~/.npm
        restore-keys: '${{ runner.OS }}-${{ matrix.node-version }}-node-

          ${{ runner.OS }}-${{ matrix.node-version }}-

          ${{ runner.OS }}-

          '
    - continue-on-error: true
      name: Install node modules
      run: 'npm install

        npm run lerna-bootstrap

        '
    - continue-on-error: true
      run: npm run lint
    strategy:
      matrix:
        node-version:
        - 18.x
        os:
        - ubuntu-latest
name: ESLint check
on:
  repository_dispatch:
    types: trigger-ga___lint.yml
